---
title: 'Assignmetn # 2 DR'
author: "Diego Rios"
date: "1/22/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
getwd
setwd("~/GitHub/QB2019_Rios/2.Worksheets/5.AlphaDiversity/")
library(vegan)
data(BCI)
```

A. Observed Richness
```{r}
S.obs <- function(x = ""){
  rowSums(x > 0) * 1
}

S.obs(BCI)
```

B. Coverage
```{r}
C <- function(x = ""){
  1 - (sum(x == 1) / rowSums(x))
}
C(BCI)
```

C. Estimated Richness
```{r}
soilbac <- read.table("~/GitHub/QB2019_Rios/2.Worksheets/5.AlphaDiversity/data/soilbac.txt",header = T, row.names = 1)
soilbac.t <- as.data.frame(t(soilbac))
soilbac1 <- soilbac.t[1,]

S.chao1 <- function(x = ""){
  S.obs(x) + (sum(x == 1)^2) / (2 * sum(x == 2))
}
S.chao1(soilbac1)

S.chao2 <- function(site = "", SbyS = ""){
  SbyS = as.data.frame(SbyS)
  x = SbyS[site,]
  SbyS.pa <- (SbyS > 0) * 1 #convert the SbyS to presence/absence
  Q1 = sum(colSums(SbyS.pa) == 1) #species observed once
  Q2 = sum(colSums(SbyS.pa) == 2) #species observed twice
  S.chao2 = S.obs(x) + (Q1^2)/(2 * Q2)
  return(S.chao2)
}
S.chao2(SbyS = soilbac, site = soilbac[,1])

S.Ace <- function(x ="", thresh = 10){
  x <- x[x>0]
  S.abund <- length(which(x > thresh))
  S.rare <- length(which (x <= thresh))
  singlt <- length(which (x == 1))
  N.rare <- sum(x[which(x <= thresh)])
  C.ace <- 1 - (singlt / N.rare)
  i <- c(1:thresh)
  count <- function(i, y){
    length(y[y == i])
  }
  a.1 <- sapply(i, count, x)
  f.1 <- (i * (i - 1)) * a.1
  G.ace <- (S.rare/C.ace)*(sum(f.1)/(N.rare*(N.rare-1)))
  S.ace <- S.abund + (S.rare/C.ace) + (singlt/C.ace) * max(G.ace,0)
  return(S.ace)
}

S.Ace(soilbac[1])

```

D. Rarefaction
```{r}
soilbac.S <- S.obs(soilbac.t)
min.N <- min(rowSums(soilbac.t))
S.rarefy <- rarefy(x = soilbac.t, sample = min.N, se = TRUE)
rarecurve(x = soilbac.t, step=20, col = "blue",cex = 0.6, las=1)
abline(0, 1, col= "red")
text(1500, 1500, "1:1", pos = 2, col = "red")
```

##4 Species Eveness

A.Visualazing Eveness: The Rank-abundance Curve (RAC)
```{r}
RAC <- function(x = ""){
  x = as.vector(x)
  x.ab = x[x > 0]
  x.ab.ranked = x.ab[order(x.ab, decreasing = TRUE)]
  return(x.ab.ranked)
}

plot.new()
site1 <- BCI[1,]

rac <- RAC(x = site1)
ranks <- as.vector(seq(1, length(rac)))
opar <- par(no.readonly = TRUE)
par(mar = c(5.1, 5.1, 4.1, 2.1))
plot(ranks, log(rac), type = "p", axes = F,
     xlab = "Rank in abundance", ylab = "Abundance",
     las = 1, cex.lab = 1.4, cex.axis = 1.25)
box()
axis(side = 1, labels = T, cex.axis = 1.25)
axis(side = 2, las = 1, cex.axis = 1.25,
     labels = c(1,2,5,10,20), at = log(c(1,2,5,10,20)))

par <- opar
```

B. Simpson's Eveness
```{r}
SimpE <- function(x = ""){
  S <- S.obs(x)
  x = as.data.frame(x)
  D <- diversity(x, "inv")
  E <- (D)/S
  return(E)
}
SimpE(site1)
```

C. Smith adn Wilson's Evenness Index
```{r}
Evar <- function(x){
  x <- as.vector(x[x > 0])
  1 - (2/pi)*atan(var(log(x)))
}
Evar(site1)
```

##5 Diversity Metrics

A. Shannon's Diversity index
```{r}
ShanH <- function(x = ""){
  H = 0
  for (n_1 in x){
    if(n_1 > 0){
      p = n_1 / sum(x)
      H = H - p*log(p)
    }
  }
  return(H)
}
ShanH(site1)

diversity(site1, index = "shannon")
```

B. Simpson's Diversity index (or Dominance index)
```{r}
SimpD <- function(x = ""){
  D = 0
  N = sum(x)
  for (n_i in x){
    D = D + (n_i^2)/(N^2)
  }
  return(D)
}

D.inv <- 1/SimpD(site1)
D.sub <- 1-SimpD(site1)
D.inv
D.sub

diversity(site1, "inv")
diversity(site1, "simp")
```

C. Fisher's alpha
```{r}
rac <- as.vector(site1[site1 > 0])
invD <- diversity(rac, "inv")
invD

Fisher <- fisher.alpha(rac)
Fisher
```

##Beyond univariate metrics

```{r}
RACresults <- radfit(site1)
RACresults

plot.new()
plot(RACresults, las = 1, cex.lab = 1.4, cex.axis = 1.25)
```

